### ISSUE TITLE
When I try to build storybook I get error:03000086:digital envelope routines::initialization error

### ISSUE THREAD

**Issue by clearly-outsane** [dannyhw/expo-storybook-starter#3]
I'm just doing `yarn build-storybook`
  
![image](https://user-images.githubusercontent.com/44093134/207358241-a20d19e3-c084-41ec-b119-e561803b1864.png)
It seems this seems to be some hash/ssl thing I'm not sure. Any ideas how to make the project build with the latest node.js version (18.x.x)

**Comment by dannyhw** [comment]
this is a node18 issue with webpack 4, you can use legacy ssl or update the webpack version

**Comment by clearly-outsane** [comment]
How can I update the webpack version to 5?

**Comment by clearly-outsane** [comment]
I tried this : https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#webpack-5 
Seems to work, you can close this issue! Thank you
