### ISSUE TITLE
it works in a stackblitz web container but only on firefox and safari eventually

### ISSUE THREAD

**Issue by rhildred** [dannyhw/expo-storybook-starter#4]
I got the expo-storybook starter working on my https://diy-pwa.dev environment. I ran:

```bash
git clone https://github.com/dannyhw/expo-storybook-starter .
npm install
npm run storybook:web
```
then reload the frame

![Screenshot 2023-11-16 at 10 47 19 AM](https://github.com/dannyhw/expo-storybook-starter/assets/346467/e57b27f1-0a35-4deb-9af5-219a4550b72b)
![Screenshot 2023-11-16 at 10 49 20 AM](https://github.com/dannyhw/expo-storybook-starter/assets/346467/1839ace0-cba0-4f0f-8dad-a282ee5e5400)

I am super excited to use this with my mobile solutions development students in a UXD class that I am teaching.

... but

there are lots of warnings, which I would prefer that students didn't have to ignore and it only works on firefox well and safari eventually. In chrome it hangs during npm install. I also tried yarn, but with yarn I got errors when I looked at the code.

I also tried it on stackblitz https://pr.new/rhildred/PROG8151Storybook. It just crashed on chrome, worked quicker on safari then it did on diy-pwa. Worked well on Firefox. I am thinking it is running out of memory in the browser. I think this based on Safari telling me that it reloaded because it used a lot of memory.

I am thinking of doing a cleanup, switching to vite and the latest storybook. I really want to get it working in such a way that a whole class can use it on firefox, chrome or safari of their choice. Do you have any bandwidth to help, or any words of advice????

**Comment by dannyhw** [comment]
@rhildred I think if you don't have a paid account that stackblitz limits your resources.

If you want to try with vite I have an example with react native web storybook using vite

**Comment by rhildred** [comment]
Thanks for the quick reply @dannyhw . I found https://github.com/dannyhw/rn-web-vite-storybook-example and tried that. Unfortunately, I didn't get further. I think that I am going to focus on the material ui kit and get them to work in figma or xd. I don't think that storybook adds that much for composing components.

**Comment by rhildred** [comment]
I had my class. They installed firefox, if they didn't already have it, and the whole class was successful on hacking https://github.com/rhildred/vite-react-native-web into a magic 8 ball app. There were some that were successful with chrome as well. You are absolutely right @dannyhw , npm install freezing on chrome seems like it, " is more of a stackblitz issue really." Overall I have been really impressed by the rate of positive change with web containers and the opportunities that they provide to make things like react-native more accessible to my students. My students struggled with the git integration in both codeflow and stackblitz, which prompted me to do my own based on isomorphic git. I also think that Storybook is a good idea. Just looking for that moment when webcontainers can run storybook smoothly for a whole class. 

Thanks so much for your responce @dannyhw !

**Comment by dannyhw** [comment]
@rhildred happy to hear that it went well and thanks for your feedback 🙏
