### ISSUE TITLE
Facing issue when running storybook on web

### ISSUE THREAD

**Issue by inkredusk** [dannyhw/expo-storybook-starter#8]
Hi,

I am facing an issue when running the command `npm run storybook:web`.

OS : Windows
Node version: v22.11.0
Expo version: 52.0.17
Storybook version: 8.4.7
Typescript: 5.3.3

Below is the error:

npm run storybook:web 

> awesomestorybookinexpo@1.0.0 storybook:web
> storybook dev -p 6006

@storybook/core v8.4.7

SB_CORE-SERVER_0007 (MainFileEvaluationError): Storybook couldn't evaluate your .storybook\main.ts file.

Original error:
Error: Transform failed with 1 error:
(define name):1:0: ERROR: Expected identifier but found "import"
    at failureErrorWithLog (\node_modules\esbuild\lib\main.js:1476:15)
    at \node_modules\esbuild\lib\main.js:755:50
    at responseCallbacks.<computed> (\node_modules\esbuild\lib\main.js:622:9)
    at handleIncomingPacket (\node_modules\esbuild\lib\main.js:677:12)
    at Socket.readFromStdout (\node_modules\esbuild\lib\main.js:600:7)
    at Socket.emit (node:events:518:28)
    at addChunk (node:internal/streams/readable:561:12)
    at readableAddChunkPushByteMode (node:internal/streams/readable:512:3)
    at Readable.push (node:internal/streams/readable:392:5)
    at Pipe.onStreamRead (node:internal/stream_base_commons:189:23)
    at loadMainConfig (.\node_modules\@storybook\core\dist\common\index.cjs:17511:11)
    at async buildDevStandalone (.\node_modules\@storybook\core\dist\core-server\index.cjs:37134:11)
    at async withTelemetry (.\node_modules\@storybook\core\dist\core-server\index.cjs:35757:12)
    at async dev (.\node_modules\@storybook\core\dist\cli\bin\index.cjs:2591:3)
    at async s.<anonymous> (.\node_modules\@storybook\core\dist\cli\bin\index.cjs:2643:74)

WARN Broken build, fix the error above.
WARN You may need to refresh the browser.

attention => Storybook now collects completely anonymous telemetry regarding usage.
This information is used to shape Storybook's roadmap and prioritize features.
You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:   
https://storybook.js.org/telemetry

Can someone please help?

**Comment by dannyhw** [comment]
Please share your main.js

**Comment by inkredusk** [comment]
@dannyhw : This is my main.ts file (am using Typescript)

import { StorybookConfig } from "@storybook/react-native";

const main: StorybookConfig = {
  stories: ["../components/**/*.stories.?(ts|tsx|js|jsx)"],
  addons: [
    "@storybook/addon-ondevice-notes",
    "@storybook/addon-ondevice-controls",
    "@storybook/addon-ondevice-backgrounds",
    "@storybook/addon-ondevice-actions",
  ],
};

export default main;

**Comment by dannyhw** [comment]
maybe try doing export default instead of `module.exports`

**Comment by inkredusk** [comment]
Hi @dannyhw ,

I tried something like this. However, still getting the same error :(

const StorybookConfig = {
  stories: [
    "../components/**/*.stories.mdx",
    "../components/**/*.stories.@(js|jsx|ts|tsx)",
  ],

  addons: [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/addon-react-native-web",
    "@storybook/addon-webpack5-compiler-babel",
    "@chromatic-com/storybook"
  ],

  framework: {
    name: "@storybook/react-webpack5",
    options: {},
  },

  docs: {},

  typescript: {
    reactDocgen: "react-docgen-typescript"
  }
};

export default StorybookConfig;

**Comment by dannyhw** [comment]
can you share the project? or a reproduction where you experience the problem?

**Comment by inkredusk** [comment]
Hi @dannyhw , I just ran this command from the Getting started section of this repo only. I have not created any new project that I can share with you.

`npx create-expo-app --template expo-template-storybook AwesomeStorybook`

After that I tried running the command : `npm run storybook:web`

**Comment by dannyhw** [comment]
@inkredusk ah ok well the template is actually a different repo here https://github.com/dannyhw/expo-template-storybook

**Comment by dannyhw** [comment]
Hmm yeah I'm seeing the issue too, thanks for reporting will look into it

**Comment by inkredusk** [comment]
Yes , its working for me now. Thanks a lot for quick response. PFB working screenshot
![image](https://github.com/user-attachments/assets/ed7b22c1-d8b1-45f1-b340-c856e8eb3f49)
